/*
DDL - DATA DEFINITION LANG.
CREATE - ALTER _ DROP
*/ -- CREATE - TABLO OLUSTURMA -

CREATE TABLE OGRENCI(OGR_NO int, OGR_ISIM VARCHAR (30),
NOTLAR real, YAS int, ADRES VARCHAR(50),
KAYIT_TARIH DATE);

-- Varolan Tablodan YEni Bir Tablo Olusturma --

CREATE TABLE OGR_NOTLARI AS
SELECT OGR_NO,
NOTLAR
FROM OGRENCI;


SELECT *
FROM OGRENCI;


SELECT *
FROM OGR_NOTLARI;